# -*- coding: utf-8 -*-
"""STUDY.md 十二个阶段（0~11）的课件内容：每页幻灯片 = 标题 + 要点 + 旁白。

结构约定：
- STAGES: list[dict]，每个 dict 含 num / slug / title / subtitle / commits / slides
- slides 里第一页 kind="title"（封面页，无 bullets）
- 普通页含 heading / bullets / narration；bullets 中以 "|" 开头表示子要点（缩进小字）
"""

STAGES = [
    # ==================== 阶段 0 ====================
    dict(
        num=0, slug="intro", title="前置知识",
        subtitle="15 分钟搞懂这个项目与四个核心概念",
        commits=[],
        slides=[
            dict(kind="title",
                 narration="你好，欢迎来到 Hui AI Agent 项目学习之旅。在正式写代码之前，我们先用十五分钟，搞清楚这个项目是做什么的，以及贯穿整个项目的几个核心概念。"),
            dict(heading="这个项目在做什么？",
                 bullets=["AI 恋爱大师：有人设、有记忆、有知识库的垂直聊天应用",
                          "HuiManus 超级智能体：自主「思考-调工具-观察」循环的 Agent",
                          "全栈配套：Spring Boot 后端 + Vue3 前端 + Docker 部署"],
                 narration="一句话介绍：用 Java 接入阿里通义千问大模型，做出两个 AI 应用。第一个是 AI 恋爱大师，它有专家人设、多轮记忆和专属知识库；第二个是 HuiManus 超级智能体，它能自己思考、调用七种工具，循环干活直到任务完成，相当于一个 Java 版的教学 Manus。此外还有 Vue3 前端和完整的部署方案。"),
            dict(heading="Spring AI 的 4 个核心概念",
                 bullets=["ChatModel：最底层的大模型客户端，一问一答",
                          "ChatClient：链式封装，可挂提示词、记忆、拦截器",
                          "Advisor：请求链上的过滤器（加记忆 / 记日志 / 拦违禁词）",
                          "Tool：告诉大模型可以调用哪些方法"],
                 narration="Spring AI 有四个核心概念。ChatModel 是最底层的大模型客户端，一问一答；ChatClient 是它的链式封装，开发应用都用它；Advisor 是挂在请求链上的过滤器，可以在发给模型前后做手脚，比如注入记忆、记日志、拦截违禁词；Tool 则是告诉大模型你还可以调用哪些方法，让它自己决定何时使用。"),
            dict(heading="两个进阶概念",
                 bullets=["RAG（检索增强生成）：先检索资料 → 塞进提示词 → 再作答",
                          "ReAct：思考一步 → 行动一步 → 看结果 → 再思考，循环到完成"],
                 narration="还有两个进阶概念。RAG，检索增强生成，先从知识库里检索相关资料，塞进提示词再让模型回答，解决模型不懂你私域知识的问题。ReAct 是智能体的运行模式：思考一步、行动一步、观察结果、再思考，循环往复直到任务完成。"),
            dict(heading="怎么学这个项目？",
                 bullets=["每个阶段：学什么 → 读哪些代码 → 动手做什么",
                          "手册在 study/ 目录（STUDY.md + 简历 + 面试自检）",
                          "每阶段末尾有 ⏪ git checkout：切回原始代码对照",
                          "先按 README 跑起来，再回来读代码"],
                 narration="这份教程按 git 提交顺序拆成了十一个阶段，每个阶段都告诉你学什么、读哪些文件、动手做什么。文字手册都在 study 目录里，包括教学文档、简历写法和面试自检题。每个阶段讲完，都可以照手册末尾的 git checkout 命令，把项目切回那一课的原始代码对照学习。开始之前，请先按 README 的快速开始，把项目跑起来。"),
        ],
    ),
    # ==================== 阶段 1 ====================
    dict(
        num=1, slug="skeleton", title="项目骨架",
        subtitle="第一次提交：一个标准的 Spring Boot 工程",
        commits=["83d1208"],
        slides=[
            dict(kind="title",
                 narration="阶段一，我们看项目的第一次提交，一个标准的 Spring Boot 工程骨架。目标很简单：认识工程结构，并能把项目启动起来。"),
            dict(heading="工程结构",
                 bullets=["父工程：spring-boot-starter-parent 3.4.4",
                          "语言：Java 21（编译启用 --enable-preview）",
                          "启动类：com.hui.huiaiagent.HuiAiAgentApplication",
                          "主配置：src/main/resources/application.yml"],
                 narration="先看 pom 文件：父工程是 Spring Boot 3.4.4，语言用 Java 21。启动类在 com.hui.huiaiagent 包下，后续所有代码都住在这个包里。主配置文件是 resources 下的 application.yml。另外注意，启动类上后来加了一个 exclude，排除了 PgVector 的自动配置，这个到 RAG 阶段再解释。"),
            dict(heading="两个必须记住的配置",
                 bullets=["端口 8123：后端所有服务都走这个口",
                          "context-path = /api：所有接口都带 /api 前缀",
                          "| 前端直连、Nginx 反代、Vite 代理都要和它对上"],
                 narration="application.yml 里有两个值必须记住。第一，端口是 8123；第二，context-path 是斜杠 api，意味着所有接口都带这个前缀。以后不管是前端直连、Nginx 反向代理还是 Vite 代理，都要和这两个值对上，配错了必然四零四。"),
            dict(heading="动手验证",
                 bullets=["启动：mvnw spring-boot:run",
                          "健康检查：http://localhost:8123/api/health",
                          "接口文档：/api/doc.html（Knife4j）"],
                 narration="动手环节：在项目根目录执行 mvnw spring-boot colon run 启动项目，然后访问 localhost 8123 端口下的 api health 接口，能返回结果，阶段一就毕业了。也可以打开 api doc 点 html，看看 Knife4j 接口文档长什么样。"),
        ],
    ),
    # ==================== 阶段 2 ====================
    dict(
        num=2, slug="invoke", title="调用大模型的 5 种方式",
        subtitle="SDK / HTTP / Spring AI / LangChain4j / Ollama",
        commits=["47e38f6", "1dbdd0b"],
        slides=[
            dict(kind="title",
                 narration="阶段二，打好调用地基。作者刻意用五个演示类，演示同一件事，让大模型说句话，的五种实现，让你直观对比从原始到高级的封装演化。代码都在 demo invoke 包下。"),
            dict(heading="方式一：裸 HTTP（HttpAiInvoke）",
                 bullets=["自己拼 URL、Header、JSON 请求体",
                          "自己解析响应 JSON",
                          "看清本质：调用大模型 = 发一个 HTTP 请求"],
                 narration="第一种，裸 HTTP。自己拼 U R L、请求头和 JSON 请求体，发出去再自己解析响应。没有任何封装，但它让你看清一件事：调用大模型的本质，就是发一个 HTTP 请求。"),
            dict(heading="方式二 & 方式三",
                 bullets=["灵积官方 SDK（SdkAiInvoke）：封装 HTTP，代码骤减",
                          "| 但绑定了具体厂商",
                          "Spring AI（SpringAiAiInvoke）★ 本项目主力",
                          "| 注入 ChatModel，一行 chatModel.call(...) 完事"],
                 narration="第二种，灵积官方 SDK，它帮你封装了 HTTP 细节，代码量骤减，但绑定了具体厂商。第三种是本项目的重中之重，Spring AI。注入 ChatModel 这个 Bean，一行 chatModel 点 call 就完成了调用。"),
            dict(heading="方式四 & 方式五",
                 bullets=["LangChain4j：另一个主流 Java AI 框架，作对比了解",
                          "Ollama：接入本地免费模型",
                          "体会：框架统一了不同模型的调用方式",
                          "| 换模型 = 换一个 ChatModel 实现，业务代码不动"],
                 narration="第四种，LangChain4j，另一个主流的 Java AI 框架，作对比了解。第五种，Ollama，接入本地免费模型。重点体会：框架统一了不同模型的调用方式，换模型只是换一个 ChatModel 实现，业务代码一行不动。"),
            dict(heading="关键设计：ChatModel 从哪来？",
                 bullets=["application.yml 配 dashscope 的 api-key",
                          "spring-ai-alibaba-starter 自动装配 dashscopeChatModel",
                          "| 后面整个项目注入的都是它",
                          "TestApiKey：拿到 Key 先跑它验证连通性"],
                 narration="这里有个关键设计：在 application.yml 里配上灵积的 api key，加上 spring-ai-alibaba-starter 依赖，Spring 就会自动装配出 dashscopeChatModel 这个 Bean，后面整个项目注入的都是它。拿到密钥后，可以先跑 TestApiKey 验证连通性。"),
            dict(heading="踩坑与动手",
                 bullets=["坑：dashscope-sdk 必须固定 2.19.1",
                          "| 升到 2.2x 与 langchain4j 冲突，报 NoSuchMethodError",
                          "动手：分别取消 @Component 注释，启动对比输出"],
                 narration="本阶段唯一的坑：dashscope SDK 必须固定用 2.19.1，升到 2.2x 会和 langchain4j 冲突，报 NoSuchMethodError，pom 里已经锁死了版本。动手环节：把这几个类上的 Component 注释分别取消，启动项目对比控制台输出。"),
        ],
    ),
    # ==================== 阶段 3 ====================
    dict(
        num=3, slug="chatclient", title="ChatClient 与 Advisor",
        subtitle="AI 恋爱大师诞生",
        commits=["5259d50"],
        slides=[
            dict(kind="title",
                 narration="阶段三，项目的第一个正式应用诞生了，AI 恋爱大师。这个阶段你将学会：ChatModel 和 ChatClient 的区别、系统提示词怎么写、以及结构化输出。核心代码是 app 包下的 LoveApp。"),
            dict(heading="ChatModel vs ChatClient",
                 bullets=["ChatModel：裸模型，只会一问一答",
                          "ChatClient：链式封装 = 模型 + 提示词 + 拦截器",
                          "| ChatClient.builder(...).defaultSystem(...).build()",
                          "开发 AI 应用，永远从 build 一个 ChatClient 开始"],
                 narration="ChatModel 是裸模型，只会一问一答；ChatClient 才是开发应用的正确姿势，它把系统提示词、拦截器都挂在身上。看 LoveApp 的构造器：用 builder 构建，设置默认系统提示词和默认 Advisor，一个带人设的聊天客户端就有了。"),
            dict(heading="系统提示词：AI 的人设",
                 bullets=["身份：深耕恋爱心理领域的专家",
                          "开场：表明身份、引导倾诉",
                          "分状态提问：单身 / 恋爱 / 已婚",
                          "引导详述：事情经过、对方反应、自身想法"],
                 narration="系统提示词决定了 AI 的人设。读一读 LoveApp 里那段话术，它包含四个要素：身份是恋爱心理专家；开场表明身份引导倾诉；按单身、恋爱、已婚三种状态分别提问；最后引导用户详述事情经过。写好这四点，人设就立住了。"),
            dict(heading="Advisor：挂在请求链上的过滤器",
                 bullets=["MessageChatMemoryAdvisor：自动注入历史对话",
                          "| 请求前查记忆、请求后写回，全由它编织",
                          "Advisor 是责任链，顺序敏感",
                          "| 后面会自定义：日志、权限、违禁词"],
                 narration="构造器里还挂了一个 MessageChatMemoryAdvisor，它会在每次请求前按会话 i d 查出历史消息注入上下文，请求后再把新消息写回去。Advisor 是责任链模式，顺序敏感，后面的阶段我们会自己写好几个。"),
            dict(heading="结构化输出：对接业务的关键",
                 bullets=["doChatWithReport：让 AI 直接返回 JSON",
                          ".call().entity(LoveReport.class)",
                          "| JSON 自动映射为 Java record（title + suggestions）",
                          "AI 输出 → 强类型对象，下游可直接用"],
                 narration="看 doChatWithReport 方法：调用 entity 并传入 LoveReport 这个 record，框架就会让 AI 直接输出 JSON，并自动映射成强类型的 Java 对象。这是 AI 应用对接业务系统的关键能力。"),
            dict(heading="动手",
                 bullets=["跑 LoveAppTest.testChat()：感受人设对话",
                          "跑 doChatWithReport()：看结构化返回",
                          "观察控制台日志里 Advisor 注入的内容"],
                 narration="动手环节：跑测试类 LoveAppTest。先跑 testChat，感受专家人设；再跑 doChatWithReport，看 JSON 怎么变成 LoveReport 对象。重点观察控制台日志里 Advisor 注入了哪些历史内容。"),
        ],
    ),
    # ==================== 阶段 4 ====================
    dict(
        num=4, slug="advisor", title="自定义 Advisor",
        subtitle="日志 / 重读增强 / 权限校验 / 违禁词",
        commits=["513c3e4", "bcab20f"],
        slides=[
            dict(kind="title",
                 narration="阶段四，自定义 Advisor。这是理解 AI 应用工程化的第一课：鉴权、风控、日志，全都要靠它。advisor 包里有四个类，难度递进。"),
            dict(heading="Advisor 的三种玩法",
                 bullets=["观察：看请求和响应（日志）",
                          "增强：改写发给模型的内容（重读）",
                          "拦截：直接拒绝请求（权限 / 违禁词）",
                          "真实项目的 AI 网关 ≈ 这三件事"],
                 narration="先记住 Advisor 的三种玩法：观察，就是看请求和响应，比如日志；增强，是改写发给模型的内容；拦截，是直接拒绝请求。真实项目里的 AI 网关，基本就是这三件事的组合。"),
            dict(heading="MyLoggerAdvisor：最简单的入门",
                 bullets=["实现 CallAdvisor 接口",
                          "adviseRequest 里看请求",
                          "next.call(...) 放行，返回值里看响应",
                          "十几行代码 = AI 调用链的 AOP"],
                 narration="MyLoggerAdvisor 是最简单的入门例子：实现 CallAdvisor 接口，在 adviseRequest 里打印请求，调用 next 点 call 放行，在返回值里打印响应。十几行代码，相当于给 AI 调用链加了个切面。"),
            dict(heading="ReReadingAdvisor：增强（改写请求）",
                 bullets=["在用户问题后面拼「让我们逐步思考…」",
                          "Re-Read / 思维链技巧，提升复杂问题准确率",
                          "学会了在 before 阶段修改用户消息"],
                 narration="ReReadingAdvisor 演示增强玩法：在用户问题后面拼一句让我们逐步思考，这是经典的思维链技巧，能提升复杂问题的准确率。它教会你如何在 before 阶段修改用户消息。"),
            dict(heading="两个拦截器：权限 + 违禁词",
                 bullets=["AuthorizedAdvisor：取 user_id，命中封禁名单直接拒绝",
                          "| 不调 next.call() = 短路返回拒绝话术",
                          "ForbiddenWordsAdvisor：违禁词检测",
                          "| 生产环境必备的内容安全"],
                 narration="最后是两个拦截器。AuthorizedAdvisor 做权限校验，从 Advisor 参数里取出 user id，命中封禁名单就直接返回拒绝话术，注意它没有调 next 点 call，这叫短路返回。ForbiddenWordsAdvisor 做违禁词检测，是生产环境必备的内容安全方案。"),
            dict(heading="动手",
                 bullets=["打开 LoveApp 构造器里 AuthorizedAdvisor 的注释",
                          "传封禁名单 Set.of(\"badGuy\")",
                          "用 AUTH_USER_ID_PARAM 模拟被封用户发消息",
                          "观察被拦截的效果"],
                 narration="动手环节：把 LoveApp 构造器里 AuthorizedAdvisor 那行注释打开，传入封禁名单 badGuy，再用 AUTH USER ID PARAM 参数模拟被封用户发消息，观察请求被拦截的效果。"),
        ],
    ),
    # ==================== 阶段 5 ====================
    dict(
        num=5, slug="memory", title="对话记忆",
        subtitle="ChatMemory 接口与三种实现",
        commits=["1913ab5", "b92588a"],
        slides=[
            dict(kind="title",
                 narration="阶段五，对话记忆。大模型本身是金鱼记忆，多轮对话全靠应用层把历史存下来再喂回去。Spring AI 把这件事抽象成了 ChatMemory 接口，本阶段写了它的三种实现。"),
            dict(heading="为什么需要对话记忆？",
                 bullets=["大模型无状态：每次请求都是「初次见面」",
                          "多轮对话 = 每次把历史消息一起发过去",
                          "ChatMemory 接口：add 写 / get 读 / clear 清",
                          "| 怎么存，随你实现"],
                 narration="大模型是无状态的，每次请求都是初次见面。所谓多轮对话，其实是每次都把历史消息一起发过去。Spring AI 把存取历史抽象成 ChatMemory 接口，怎么存随你实现。"),
            dict(heading="三个实现类（策略模式）",
                 bullets=["InMemoryChatMemory：框架自带，重启就没",
                          "FileBasedChatMemory：一个会话一个文件（Kryo 序列化）",
                          "MysqlChatMemory：一条消息一行记录",
                          "| 同一接口，构造器里一行切换"],
                 narration="项目里有三个实现：框架自带的 InMemory，存内存重启就没；手写的 FileBased，一个会话一个文件，用 Kryo 序列化；还有手写的 MysqlChatMemory，一条消息一行记录。同一个接口，策略模式，一行代码切换。"),
            dict(heading="chat_memory 表：数据模型",
                 bullets=["conversation_id：会话 id（对应业务 chatId）",
                          "role：USER / ASSISTANT / SYSTEM",
                          "content：消息原文",
                          "自增主键 id：天然记录消息先后顺序"],
                 narration="看 chat memory 建表脚本，四个字段就够：conversation id 对应业务里的 chatId；role 记录谁说的；content 存原文；自增主键天然记录消息顺序。这就是多轮对话数据模型的全部。"),
            dict(heading="记忆是怎么被用起来的？",
                 bullets=["LoveApp 挂上 MessageChatMemoryAdvisor(chatMemory)",
                          "| 请求前按 chatId 查历史 → 注入上下文",
                          "| 请求后把新消息写回",
                          "你只管写实现类，编织过程框架包办"],
                 narration="记忆是怎么被用起来的？LoveApp 构造器里挂了 MessageChatMemoryAdvisor，它负责在请求前按 chatId 查历史注入上下文，请求后把新消息写回去。你只管实现 ChatMemory 接口，编织过程框架包办。"),
            dict(heading="动手",
                 bullets=["切换到 MysqlChatMemory（构造器改一行）",
                          "同一个 chatId 连问两句（第二句依赖第一句）",
                          "SELECT * FROM chat_memory 看落库数据",
                          "再切 FileBased，看序列化文件"],
                 narration="动手环节：把 LoveApp 构造器切换到 MysqlChatMemory，用同一个 chatId 连续问两句话，第二句要依赖第一句的上下文，然后查表看落库的数据。再切换 FileBased，看看生成的序列化文件。"),
        ],
    ),
    # ==================== 阶段 6 ====================
    dict(
        num=6, slug="rag", title="RAG 检索增强",
        subtitle="8 个提交的知识库进化史",
        commits=["3c8d159", "4fba4e9", "e8f05e5", "79c72e1", "83b1e41",
                 "7b46e09", "7a1c1f8", "733add7", "9d3ebbe", "3c485a8", "77a34fc"],
        slides=[
            dict(kind="title",
                 narration="阶段六，RAG 检索增强。这是提交最多的阶段，知识库的每个环节都被拆成了独立提交，强烈建议逐个 git show 对比学习。"),
            dict(heading="RAG 三步曲（先背下来）",
                 bullets=["① 离线写入：文档 → 切分 → 向量化 → 存入向量库",
                          "② 在线检索：用户问题 → 向量化 → 相似度 TopK",
                          "③ 增强回答：命中文档拼进提示词 → 模型作答"],
                 narration="RAG 三步曲，先背下来。第一步离线写入：文档切分、向量化、存入向量库；第二步在线检索：把用户问题也向量化，做相似度搜索取回最相关的几段；第三步增强回答：把命中的文档拼进提示词，让模型结合资料作答。"),
            dict(heading="写入侧：文档到向量库",
                 bullets=["LoveAppDocumentLoader：读 3 份 md + 打 status 元数据",
                          "| status = 单身 / 恋爱 / 已婚，为过滤检索做准备",
                          "MyTokenTextSplitter：Token 切分，控制段落长度",
                          "MyKeywordEnricher：用 AI 自动补关键词元数据",
                          "SimpleVectorStore（内存，默认）/ PgVector（生产）"],
                 narration="写入侧：LoveAppDocumentLoader 读取 document 目录下三份 Markdown 知识文档，并按文件名给每段打上单身、恋爱、已婚的状态元数据；MyTokenTextSplitter 负责切分控制段落长度；MyKeywordEnricher 用 AI 自动补关键词。向量库默认用内存版 SimpleVectorStore，生产可以换成 PgVector。"),
            dict(heading="检索侧：让搜得更准",
                 bullets=["QueryRewriter 查询重写：口语化问题 → 独立完整问题",
                          "检索配置：按 status 过滤 + 相似度阈值 0.5 + topK 3",
                          "空结果兜底：检索不到就回「只能回答恋爱问题」",
                          "MultiQueryExpander：一题改多角度分别检索"],
                 narration="检索侧全是让搜得更准的手段：QueryRewriter 把口语化、带闲聊的问题重写成独立完整的检索问题；检索配置支持按状态过滤、相似度阈值和 TopK；检索结果为空时有兜底话术，不瞎答；查询扩展还能把一个问题改写成多个角度分别检索。"),
            dict(heading="三个真实的坑",
                 bullets=["DashScope Embedding 单次最多 25 条文本 → 必须分批入库",
                          "查询重写默认英文提示词，会把中文问题翻译成英文",
                          "| 换中文模板，且必须保留 {query} {target} 占位符"],
                 narration="本阶段踩了三个真实的坑。第一，灵积的向量化接口单次最多二十五条文本，入库必须分批。第二，查询重写默认提示词是英文的，会把中文问题翻译成英文，要换成中文模板。第三，自定义模板必须保留 query 和 target 两个占位符，否则 builder 校验直接报错。"),
            dict(heading="动手",
                 bullets=["跑 LoveAppTest.doChatWithRag()",
                          "问一个只有知识库里才有答案的问题",
                          "对比 doChatWithRagQueryWriter() 的重写日志",
                          "git show 逐个对比这 8 个提交"],
                 narration="动手环节：跑 doChatWithRag，问一个只有知识库里才有答案的问题，感受检索增强的效果；再对比 doChatWithRagQueryWriter，观察日志里重写前后的问题差别。最后，逐个 git show 这八个提交，看知识库一点点进化。"),
        ],
    ),
    # ==================== 阶段 7 ====================
    dict(
        num=7, slug="tools", title="工具调用（Tool Call）",
        subtitle="给 AI 装上手脚",
        commits=["abe317c", "e572071", "c5f78f2", "563cb68",
                 "0311275", "b33e133", "8fcf40d"],
        slides=[
            dict(kind="title",
                 narration="阶段七，工具调用。前面的 AI 只会说，这一阶段让 AI 会做。你只要用 Tool 注解把方法标出来，大模型就会自己决定何时调用、传什么参数。"),
            dict(heading="@Tool 注解：两行注解一个工具",
                 bullets=["@Tool(description=...) 标在方法上",
                          "description 写得越清楚，模型调用越准",
                          "@ToolParam 描述每个参数的含义",
                          "工具类不走 Spring 注入，由注册类手动 new"],
                 narration="定义一个工具非常简单：方法上标 Tool 注解写清楚描述，参数上标 ToolParam。记住一条黄金法则：description 写得越清楚，模型调用越准。另外注意，工具类都是普通类，不走 Spring 注入，由注册类手动 new 出来。"),
            dict(heading="七个工具一览（tools 包）",
                 bullets=["FileOperationTool：读写本地文件",
                          "WebSearchTool：SearchAPI 搜百度，返回前 5 条",
                          "WebScrapingTool：Jsoup 抓网页正文",
                          "TerminalOperationTool：执行终端命令（区分系统）",
                          "ResourceDownloadTool：下载网络资源",
                          "PDFGenerationTool：iText 生成 PDF（中文字体）+ TerminateTool"],
                 narration="七个工具快速过一遍：文件读写、联网搜索、Jsoup 抓网页、执行终端命令、下载网络资源、iText 生成 PDF，注意 PDF 要加中文字体依赖，不然全是方块；最后是 TerminateTool 终止工具，它是下一阶段智能体循环的刹车，先记住这个伏笔。"),
            dict(heading="ToolRegistration：工具注册中心",
                 bullets=["@Bean ToolCallback[] allTools()",
                          "ToolCallbacks.from(7 个工具实例)",
                          "| 统一转成 ToolCallback 数组注入容器",
                          "工厂 + 注册 + 适配器模式（注释里有讲解）"],
                 narration="ToolRegistration 是注册中心：一个 Bean 方法，用 ToolCallbacks 点 from，把七个工具实例统一转成 ToolCallback 数组，注入 Spring 容器。作者在注释里专门写了这里用到的设计模式，值得一看。"),
            dict(heading="调用链路：AI 只出意图，执行在你进程",
                 bullets=["模型返回：「我要调 searchWeb，参数是 xxx」",
                          "框架反射执行 Java 方法",
                          "结果回传模型 → 组织成自然语言答复",
                          "执行永远在你的 Java 进程里，安全可控"],
                 narration="理解完整链路：模型收到问题和工具描述后，返回的是调用意图，比如我要调 searchWeb，参数是什么；框架通过反射真正执行你的 Java 方法；结果回传给模型，它再组织成自然语言答复。所以执行永远在你的进程里，安全可控。"),
            dict(heading="动手",
                 bullets=["跑 LoveAppTest.doChatWithTools()",
                          "输入「帮我搜一下今天杭州的天气」",
                          "观察日志：模型发起的工具调用与参数",
                          "挑战：自己写一个「获取当前时间」工具并注册"],
                 narration="动手环节：跑 doChatWithTools，输入帮我搜一下今天杭州的天气，观察日志里模型发起的工具调用和参数。挑战题：自己写一个获取当前时间的工具，在注册类里加上，看模型会不会用它。"),
        ],
    ),
    # ==================== 阶段 8 ====================
    dict(
        num=8, slug="manus", title="手写 Manus 智能体",
        subtitle="全项目最核心：ReAct 循环的四层实现",
        commits=["bd434b1"],
        slides=[
            dict(kind="title",
                 narration="阶段八，全项目的高光部分：不依赖任何 Agent 框架，用四个类手写一个迷你 Manus。请务必按继承链自上而下读代码。"),
            dict(heading="四层继承：自上而下读",
                 bullets=["BaseAgent：执行循环 + 状态机 + SSE 流式输出",
                          "ReActAgent：定义 think() / act() 抽象",
                          "ToolCallAgent：思考选工具、行动执行工具（难点）",
                          "HuiManus：最终智能体，组装提示词与工具"],
                 narration="四个类的继承链：BaseAgent 打地基，管理执行循环和状态机；ReActAgent 定义思考和行为两个抽象方法；ToolCallAgent 是最难的一层，把工具调用真正落地；HuiManus 是最终产品，只做组装。读代码时自上而下，思路最顺。"),
            dict(heading="BaseAgent：循环 + 状态机",
                 bullets=["AgentState：IDLE → RUNNING → FINISHED / ERROR",
                          "for (i < maxSteps && state != FINISHED) step()",
                          "| 「步数上限 + 完成标记」双保险，防无限循环烧钱",
                          "runStream()：SseEmitter + 异步线程推每一步结果"],
                 narration="BaseAgent 的 run 方法是心脏：一个 for 循环，条件是步数小于上限，并且状态不是已完成。双保险防止 AI 无限循环烧钱。状态机有四个状态：空闲、运行、完成、错误。runStream 方法用 SseEmitter 加异步线程，把每一步结果实时推给前端。"),
            dict(heading="ReActAgent：一步 = 思考 + 行动",
                 bullets=["step() = think() + act()",
                          "think()：让大模型决定下一步",
                          "act()：执行思考产生的动作",
                          "这就是 ReAct 模式的全部骨架"],
                 narration="ReActAgent 只做一件事：把一步拆成思考和行动。think 让大模型决定下一步，act 执行思考产生的动作。三行代码，就是 ReAct 模式的全部骨架。"),
            dict(heading="ToolCallAgent：两个关键设计（难点）",
                 bullets=["think()：消息历史 + 引导词 + 全部工具 → 模型决策",
                          "act()：ToolCallingManager 执行，结果追加进消息列表",
                          "① withProxyToolCalls(true)：关内置执行，自己维护上下文",
                          "② 检测 doTerminate → 状态置 FINISHED，循环结束"],
                 narration="ToolCallAgent 是难点。think 把消息历史、引导词和全部工具发给模型；act 用 ToolCallingManager 执行工具，并把结果追加进消息列表，这就是观察。两个关键设计：第一，withProxyToolCalls 设为 true，关掉框架内置的工具执行，因为 Agent 要自己维护跨多轮的上下文；第二，执行完检测是否调用了 terminate 工具，调了就把状态置为完成，循环结束。"),
            dict(heading="一次任务的完整生命",
                 bullets=["「帮我做上海约会攻略并生成 PDF」",
                          "think：选 WebSearchTool → act：搜索结果入消息",
                          "若干轮后：写文件 → 生成 PDF → doTerminate",
                          "每个 Step 都通过 SSE 实时推给了前端"],
                 narration="串起来看一次任务：用户说，帮我做上海约会攻略并生成 PDF。模型先选搜索工具，结果进入消息历史；再选文件工具写攻略，再选 PDF 工具生成文件；最后调用 terminate，循环结束。每个 Step 都通过 SSE 实时推给了前端。"),
            dict(heading="动手",
                 bullets=["跑 agent/huiManusTest.java",
                          "给它一个多步任务（搜索 + 写文件 + 生成 PDF）",
                          "挑战：加一个自己的工具，看 Manus 会不会用"],
                 narration="动手环节：跑 huiManusTest 测试类，给智能体一个多步任务，比如搜索资料、写成文件、再生成 PDF，观察它怎么一步步完成。挑战题：加一个你自己的工具，看 Manus 会不会自主用它。"),
        ],
    ),
    # ==================== 阶段 9 ====================
    dict(
        num=9, slug="api", title="接口服务化与流式输出",
        subtitle="Flux / SseEmitter 与跨域",
        commits=["1419c4d", "c377b50"],
        slides=[
            dict(kind="title",
                 narration="阶段九，把 AI 能力变成 HTTP 接口，并实现 AI 应用的标配：流式输出。用户等不了三十秒再看一大段字，要一个字一个字往外蹦。"),
            dict(heading="两种流式方案（控制器里都有）",
                 bullets=["WebFlux：返回 Flux<String>，响应式流",
                          "| produces = TEXT_EVENT_STREAM_VALUE",
                          "Servlet MVC：SseEmitter，手动挡",
                          "| Flux.subscribe(...) 转投给 Emitter",
                          "殊途同归，按项目技术栈选"],
                 narration="控制器里两种方案都写了，专门供你对比。WebFlux 方案直接返回 Flux，声明 produces 为 text event stream；传统 MVC 则用 SseEmitter 手动挡，把 Flux 订阅后逐条转投给 Emitter。殊途同归，按技术栈选即可。"),
            dict(heading="有状态 Agent：每次请求 new 一个",
                 bullets=["/ai/manus/chat 里每次 new HuiManus(...)",
                          "Agent 有状态：消息列表 + 状态机",
                          "单例会串会话 —— 重要设计细节",
                          "与 LoveApp 无状态 ChatClient 形成对比"],
                 narration="注意一个重要细节：manus 接口里每次请求都 new 一个 HuiManus。因为 Agent 是有状态的，内部有消息列表和状态机，如果做成单例，不同用户的会话就串了。这和 LoveApp 那个无状态的 ChatClient 形成鲜明对比。"),
            dict(heading="跨域：CorsConfig",
                 bullets=["开发环境前端直连 localhost:8123 → 跨域请求",
                          "allowCredentials(true) 必须配 allowedOriginPatterns",
                          "| 直接用 * 会冲突报错",
                          "生产同域部署（Nginx 反代）后不再依赖"],
                 narration="开发环境前端直连 8123 端口，属于跨域请求，所以后端的 CorsConfig 是必需的。一个高频坑：开了 allowCredentials，就必须用 allowedOriginPatterns，直接用星号会冲突报错。生产环境前后端同域部署后，就不再依赖它了。"),
            dict(heading="动手",
                 bullets=["curl -N 请求 /api/ai/manus/chat",
                          "给它一个任务：把「你好」写入 hello.txt",
                          "观察 SSE 逐段输出的每个 Step",
                          "对比 /love_app/chat/sse 的逐字输出"],
                 narration="动手环节：用 curl 加 N 参数请求 manus 接口，让它把你好二字写入文件，观察 SSE 逐段输出的每个步骤；再对比恋爱大师接口的逐字输出，体会两种流式形态的差别。"),
        ],
    ),
    # ==================== 阶段 10 ====================
    dict(
        num=10, slug="frontend", title="Vue3 前端",
        subtitle="消费 SSE 流的正确姿势",
        commits=["55c89f0"],
        slides=[
            dict(kind="title",
                 narration="阶段十，Vue3 前端。重点不是 Vue 语法，而是前端怎么消费后端的 SSE 流。重点读四个文件。"),
            dict(heading="四个核心文件",
                 bullets=["src/utils/sse.js：fetch 手写 SSE 解析（灵魂）",
                          "src/api/ai.js：聊天接口封装 + 环境地址切换",
                          "src/components/ChatRoom.vue：通用聊天室组件",
                          "src/views/：主页 / 恋爱大师 / Manus 三个页面"],
                 narration="四个核心文件：sse.js 是灵魂，基于 fetch 手写了 SSE 解析；api 目录下的 ai.js 封装两个聊天接口，并处理开发、生产环境的地址切换；ChatRoom 是通用聊天室组件，两处复用；views 下是三个页面。"),
            dict(heading="手写 SSE 解析：通用流式范式",
                 bullets=["fetch → response.body.getReader()",
                          "按两个换行切分 SSE 事件",
                          "最后一段可能不完整 → 留在 buffer 等下一帧",
                          "不用 EventSource：不感知流结束、难做「停止生成」"],
                 narration="sse.js 的解析套路值得背下来：fetch 拿到响应后，用 getReader 逐帧读取；SSE 事件用两个换行分隔；最后一段可能是残包，留在缓冲区等下一帧。为什么不用原生 EventSource？因为它不感知流的正常结束，也做不了停止生成这类主动控制。"),
            dict(heading="环境地址与跨域",
                 bullets=["开发：直连 http://localhost:8123/api（跨域）",
                          "| 所以后端必须有 CorsConfig",
                          "生产：相对路径 /api（同域部署）",
                          "vite.config.js 的 /api 代理只是备用方案"],
                 narration="ai 点 js 里，开发环境直连 localhost 8123，是跨域请求，这正是后端要写 CorsConfig 的原因；生产环境用相对路径，走同域部署。vite 配置里的代理只是备用方案。"),
            dict(heading="打字机效果：没有魔法",
                 bullets=["每收到一个 chunk → 追加到当前消息 buffer",
                          "Vue 响应式自动触发重渲染",
                          "markdown.js 把 AI 输出渲染成 HTML",
                          "/love 是逐字流，/manus 是按 Step 推送"],
                 narration="打字机效果没有任何魔法：每收到一个 chunk 就追加到当前消息的缓冲区，Vue 的响应式系统自动触发重渲染。markdown 工具负责把 AI 输出渲染成 HTML。最后对比两个页面：恋爱大师是逐字流，Manus 是按步骤推送。"),
            dict(heading="动手",
                 bullets=["npm install && npm run dev",
                          "同时打开 /love 和 /manus 对比",
                          "精读 utils/sse.js 的切分与 buffer 逻辑",
                          "挑战：加「停止生成」按钮（AbortController）"],
                 narration="动手环节：安装依赖后启动开发服务器，同时打开恋爱大师和 Manus 页面，对比两种流式形态；精读 sse.js 的事件切分逻辑。挑战题：利用 AbortController，给聊天室加一个停止生成按钮。"),
        ],
    ),
    # ==================== 阶段 11 ====================
    dict(
        num=11, slug="deploy", title="部署上线",
        subtitle="Docker 多阶段构建与密钥安全",
        commits=["7fa8fdf", "8a317ff"],
        slides=[
            dict(kind="title",
                 narration="最后一个阶段，部署上线。AI 应用上生产要抓两件大事：镜像瘦身和密钥安全。"),
            dict(heading="Docker 多阶段构建",
                 bullets=["阶段一：maven 镜像里打 jar",
                          "阶段二：纯 JRE 镜像只拷贝 jar",
                          "镜像 1GB+ → 几百 MB，Serverless 冷启动更快",
                          "前端：构建静态文件 + Nginx 托管 + 反代 /api"],
                 narration="看根目录的 Dockerfile：第一阶段在 maven 镜像里打包；第二阶段只把 jar 拷进纯 JRE 镜像。镜像从一吉多瘦到几百兆，Serverless 冷启动更快。前端则构建成静态文件交给 Nginx 托管，并把 api 反代到后端。"),
            dict(heading="三层配置隔离（值得抄走）",
                 bullets=["application.yml：非敏感配置，进 git",
                          "application-local.yml：本地密钥",
                          "| .gitignore + .dockerignore 双重忽略，永不进仓库和镜像",
                          "生产密钥：一律部署平台环境变量注入",
                          "| 环境变量优先级高于 jar 内所有 yml"],
                 narration="密钥管理是三层隔离的哲学：application.yml 放非敏感配置进 git；application-local.yml 放本地密钥，被 gitignore 和 dockerignore 双重忽略，永不进仓库和镜像；生产密钥一律在部署平台用环境变量注入，它的优先级高于 jar 包里的所有配置文件。"),
            dict(heading="两个小而美的细节",
                 bullets=["-XX:MaxRAMPercentage=75.0",
                          "| JVM 堆按容器内存自适应，适配 Serverless 限额",
                          "密钥对应环境变量：SPRING_AI_DASHSCOPE_API_KEY 等",
                          "| 环境变量命名规则：点换下划线、全大写"],
                 narration="还有两个小而美的细节：JVM 参数 MaxRAMPercentage 设为 75，让堆内存按容器配额自适应，适配 Serverless 的内存限制；Spring 的环境变量命名规则也记一下，配置点换下划线再全大写，比如 dashscope 的 api key 就写成 SPRING AI DASHSCOPE API KEY。"),
            dict(heading="结业：下一步去哪？",
                 bullets=["11 道自测题（见 study/STUDY.md 结尾）全部答出来 = 毕业",
                          "进阶：给 Manus 加记忆 / 工具并行执行",
                          "进阶：RAG 检索质量评测、调用可观测",
                          "git log 看看 —— 每次提交都是你走过的脚印"],
                 narration="到这里，从调一个大模型接口，到上线一个智能体应用，你全部走通了。回头看看 git log，每一次提交都是你走过的脚印。去把 study 目录里 STUDY 手册结尾的十一道自测题做完，全部答出来，就算正式毕业。学习愉快，我们江湖再见！"),
        ],
    ),
]
